metrics:
  # Set flag to evaluate model weights; if False, then final updated model will be evaluated
  use_callback: True
  # Choose the training cycle for the evaluation. Can be: 1, 2, ...
  saved_training_cycle: 2
  # Provide path to saved model checkpoints.
  chkp_save_path: checkpoint
  # Fill model_params if computing metrics_only on a pre-trained model
  # ID name
  id_name: _sample_w_bis1_2k 
  #  id_name: -coherent_euclid_2000stars
  # Path to Trained Model
  trained_model_path: /feynman/work/dap/lcs/jw274171/Euclid/Model_Alex/wf-outputs-202307041437/
  # /disk/xray0/tl3/outputs/refactor_wf/wf-outputs/wf-outputs-202307041437/ 
  # trained_model_path: /Users/jenniferpollack/Projects/wf-outputs/wf-outputs-202306011821/
  # Name of Trained Model Config file
  trained_model_config: config/training_config.yaml 
  #Evaluate the polychromatic RMSE metric.
  eval_poly_metric_rmse: False
  #Evaluate the monchromatic RMSE metric.
  eval_mono_metric_rmse: False
  #Evaluate the shape results.
  eval_test_shape_sr_metric_rmse: False
  #Evaluate the OPD RMSE metric.
  eval_opd_metric_rmse: False
  #Evaluate the super-resolution and the shape RMSE metrics for the train dataset.
  eval_train_shape_sr_metric_rmse: False
  # save predicted PSF images
  save_psf_images: False
  # save monochromatic shapes
  eval_mono_shape: True
  # super resolution or not ?
  save_psf_super_res: False
  ground_truth_model:
    model_params:
      #Model used as ground truth for the evaluation. Options are: 'poly', 'physical'.
      model_name: poly 

      # Evaluation parameters
      #Number of bins used for the ground truth model poly PSF generation
      n_bins_lda: 20

      #Downsampling rate to match the oversampled model to the specified telescope's sampling.
      output_Q: 3

      #Oversampling rate used for the OPD/WFE PSF model.
      oversampling_rate: 3 
    
      #Dimension of the pixel PSF postage stamp
      output_dim: 32
        
      #Dimension of the OPD/Wavefront space."
      pupil_diameter: 256

      #Boolean to define if we use sample weights based on the noise standard deviation estimation
      use_sample_weights: False

      #Interpolation type for the physical poly model. Options are: 'none', 'all', 'top_K', 'independent_Zk'."
      interpolation_type: None

      # SED intepolation points per bin
      sed_interp_pts_per_bin: 0

      # SED extrapolate 
      sed_extrapolate: False
      
      # SED interpolate kind
      sed_interp_kind: linear

      # Standard deviation of the multiplicative SED Gaussian noise.
      sed_sigma: 0

      #Limits of the PSF field coordinates for the x axis.
      x_lims: [0.0, 1.0e+3]
      
      #Limits of the PSF field coordinates for the y axis.
      y_lims: [0.0, 1.0e+3]
      
      # Hyperparameters for Parametric model 
      param_hparams:
        # Parameter for the l2 loss function for the Optical path differences (OPD)/WFE
        l2_param: 0.
      
        #Zernike polynomial modes to use on the parametric part.
        n_zernikes: 45
      
        #Max polynomial degree of the parametric part.  chg to max_deg_param
        d_max: 2  

        #Flag to save optimisation history for parametric model
        save_optim_history_param: True

      # Hyperparameters for non-parametric model
      nonparam_hparams:
        #Max polynomial degree of the non-parametric part. chg to max_deg_nonparam
        d_max_nonparam: 5 

        # Number of graph features
        num_graph_features: 10
        
        #L1 regularisation parameter for the non-parametric part."
        l1_rate: 1.0e-8

        #Flag to enable Projected learning for DD_features to be used with `poly` or `semiparametric` model.
        project_dd_features: False

        #Flag to reset DD_features to be used with `poly` or `semiparametric` model
        reset_dd_features: False

        #Flag to save optimisation history for non-parametric model
        save_optim_history_nonparam: true 

  metrics_hparams:
    # Batch size to use for the evaluation.
    batch_size: 16
  
    #Save RMS error for each super resolved PSF in the test dataset in addition to the mean across the FOV."
    #Flag to get Super-Resolution pixel PSF RMSE for each individual test star. 
    #If `True`, the relative pixel RMSE of each star is added to ther saving dictionary.
    opt_stars_rel_pix_rmse: False
  
    ## Specific parameters
    # Parameter for the l2 loss of the OPD.
    l2_param: 0.

    ## Define the resolution at which you'd like to measure the shape of the PSFs
    #Downsampling rate from the high-resolution pixel modelling space.
    # Recommended value: 1
    output_Q: 1

    #Dimension of the pixel PSF postage stamp; it should be big enough so that most of the signal is contained inside the postage stamp. 
    # It also depends on the Q values used.
    # Recommended value: 64 or higher
    output_dim: 64
      

